# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-03 11:12
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='mails',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('addressfrom', models.TextField(blank=True, null=True)),
                ('addressto', models.TextField(blank=True, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mails',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ml_topics',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('probs', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=5), size=None)),
                ('topics', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
            ],
            options={
                'db_table': 'ml_topics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, null=True)),
                ('department', models.TextField(blank=True, null=True)),
                ('datebegin', models.DateTimeField(blank=True, null=True)),
                ('dateend', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
