# Generated by Django 2.0.2 on 2018-04-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now=True)),
                ('NameFrom', models.CharField(blank=True, max_length=100)),
                ('AddressFrom', models.CharField(blank=True, max_length=100)),
                ('NameTo', models.CharField(blank=True, max_length=100)),
                ('AddressTo', models.CharField(blank=True, max_length=100)),
                ('Subject', models.CharField(blank=True, max_length=100)),
                ('Message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=100)),
                ('Address', models.CharField(blank=True, max_length=100)),
                ('DateBegin', models.DateTimeField(auto_now=True)),
                ('DateEnd', models.DateTimeField(auto_now=True)),
                ('Department', models.IntegerField(blank=True)),
            ],
        ),
    ]
