# Generated by Django 2.0.2 on 2018-04-04 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0002_auto_20180404_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mails',
            name='Date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='DateBegin',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='users',
            name='DateEnd',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
