version: "3"
services: 
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=maildiscovery
      - POSTGRES_PASSWORD=mailpass
      - POSTGRES_NAME=maildata
      - POSTGRES_DB=maildata
    volumes:
      - maildiscovery:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=maildiscovery
      - POSTGRES_PASSWORD=mailpass
      - POSTGRES_DB=maildata
    depends_on:
      - db
  node:
    image: "node:9"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  maildiscovery:

