version: "3"
services: 
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=db_usr
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_NAME=my_db
      - POSTGRES_DB=my_db
    volumes:
      - /home/Innprak/install/django/data/postgres:/var/lib/postgresql/data

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=db_usr
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=my_db
    depends_on:
      - db

